### ISSUE TITLE
Double messages sending at one click

### ISSUE THREAD

**Issue by Carson12345** [zendesk/sunshine-conversations-web#638]
Hi, 

When my users send message through the web sdk, occasionally their message get sent for 2 times, one immediately after the another. 

This happened like 20 times in the past 3 months, it happened the most in Internet Explorer and Edge, then Chrome.

Still I do not have a way to reproduce this error at wish. The error had happened most in this situation:

1. Idling the website for over 20 minutes before sending a message
2. At the other time it just happends randomly.

May I know if anyone also face this too?

<img width="263" alt="screen shot 2017-09-29 at 11 32 31 pm" src="https://user-images.githubusercontent.com/22004238/31024196-dcfcdf2e-a570-11e7-8591-ca3c0fe22f30.png">
<img width="445" alt="screen shot 2017-09-29 at 11 34 14 pm" src="https://user-images.githubusercontent.com/22004238/31024195-dcd0b2f0-a570-11e7-8238-aacd216a6ca9.png">

**Comment by DataWearsAHood** [comment]
Hello Carson,

Doing a bit of housekeeping here, and it looks like there was already a support ticket filed/resolved, so we'll be closing this one.
While the ticket's closing notes do mention that this issue was not reproducible as of v4.29.21, I also found an entry in [our release notes](https://github.com/zendesk/sunshine-conversations-web/releases/tag/4.16.3) that seem to match your reported symptoms: https://github.com/zendesk/sunshine-conversations-web/releases/tag/4.16.3
