### ISSUE TITLE
Send custom data 

### ISSUE THREAD

**Issue by mfvitale** [zendesk/sunshine-conversations-web#667]
Hi,

is there a way to send custom data on conversation start/ chat opening?

I found:
```
Smooch.sendMessage({
    type: 'text',
    text: 'hello'
});
```

Which types are supported? Is there the possibility to send a postback with custom data?

Thanks, 
Mario.

**Comment by mspensieri** [comment]
`Smooch.sendMessage` is for sending a message as the SDK user, are you asking if there is a way to send a first message as the app maker? You might want to check out the [business initiated conversations](https://docs.smooch.io/guide/business-initiated-conversations/) guide

**Comment by mfvitale** [comment]
> `Smooch.sendMessage` is for sending a message as the SDK user, are you asking if there is a way to send a first message as the app maker? You might want to check out the [business initiated conversations](https://docs.smooch.io/guide/business-initiated-conversations/) guide

I need to pass some data on the chat opening. Is there a way?

**Comment by spasiu** [comment]
@mfvitale 
You can append metadata to the user with this method https://github.com/smooch/smooch-web#updateuseruser

```
Smooch.updateUser({
  properties: {
    myCustomProp: true
  }
})
```

 and then call this method https://github.com/smooch/smooch-web#startconversation to start the conversation and send a `conversation:start` webhook event to your server. On the Server, you can retrieve the appUser record to see whatever custom data was attached.

You can also append custom data to any of the messages sent through the `Smooch.sendMessage` method with _metadata_ like so:
```
Smooch.sendMessage({
  type: 'text',
  text: 'hello',
  metadata: {
    myCustomProp: true
  }
})
```

This metadata will be received in a webhook event on your server as part of the message.

We don't yet have a generic method for sending data whenever you want, currently, you can only do it through the app user's profile or the message metadata.

And the only events to let you know that data exists on the server are the message events and the one time only per app user `conversation:start` event. If you need something more complex you'll have to create it outside of the smooch SDK.

**Comment by mfvitale** [comment]
@spasiu 

I have tried with your suggest:

```
Smooch.updateUser({
         properties: {
           prop1: "val1",
           pro2: "val2"
         }
});
Smooch.startConversation();
```

But on the conversation:start trigger i don't find the properties:
![screenshot from 2018-10-15 16-28-49](https://user-images.githubusercontent.com/2572323/46957754-82087980-d098-11e8-9812-a436399a29cb.png)

If a wrote a message then the properties are present. Any suggestion?


Thank,
Mario.

**Comment by DataWearsAHood** [comment]
Hello!

When setting `includeFullAppUser: true` in your webhook config, these properties should be passed through with the webhook.
I've filed this as a to the fix pipeline; You can subscribe to this repo's releases page to know once it's been fixed!


In case others are wondering, there are 2 options:
1. update the appUser's properties (client-side) and fetch the appUser record (server-side) when receiving conversation:start
1. pass the metadata (from client-side) in a hidden message (requiring all the steps below):

- implement a `beforeDisplay` delegate to hide messages (`return null;`) when messages contain (e.g.) `metadata: { hideMe: true}`
- instead of calling `startConversation()`, call `sendMessage()` with `message.metadata: { hideme: true, new_convo: true, customprop1: "v1", customprop2: "v2" ... }`
- watch for user message with `new_convo: true` on the server-side and process as you would a `conversation:start` event
