### ISSUE TITLE
Issue with Embeddeed Mode

### ISSUE THREAD

**Issue by bradconnolly** [zendesk/sunshine-conversations-web#689]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

-   [X] bug report
-   [ ] support request => Please do not submit support request here, see note at the top of this template.

----

**What is the current behavior?**

When following the documentation for how to use the embedded mode I am seeing some issues.

index.html
```
<div id="embed" style="height: 600px; width: 75%; margin-left: auto; margin-right: auto; margin-top: 10px; border:0.5px solid black;"> </div>
```

index.js
```
Smooch.init({
  integrationId: '<integration_id>',
  embedded: true,
}).then(() => {
  console.log('After Init');
  Smooch.render(document.getElementById('embed'));
});
```

What I am seeing is when I have **embedded** set to true **AND** call the `Smooch.render` method in the then method, the then method does not run at all. I don't see the console log for 'After Init' and the widget is not shown.

When I remove the render method call, I see the console log for 'After Init', but since I am not rendering it the widget does not appear.

When I remove **embedded: true** from the configuration settings then the widget appears as the floating button.

----

**What is the expected behavior?**

Based on the [Embedded Mode Documentation](https://github.com/zendesk/sunshine-conversations-web#embedded-mode), I would expect that when the embedded flag is set to true and we run the `Smooch.render` method in the then method, the widget would render within the specified DOM element.

----

**Please tell us about your environment:**

-   Delivery method: NPM
-   Version: 5.3.9
-   Browser: Chrome
-   OS: OS X 10.15.7

----

Thank you very much for your help! 😄

**Comment by adamzendesk** [comment]
Hi Brad! 

My apologies about the confusion here - the documentation is currently incorrect and I have filed a request with our documentation team to have this corrected. The issue is that when using embedded mode in the latest versions of the SDK init is not called _until_ render has been called, which means it never gets there.

When you get a moment could you please try the following code:

index.html
```
 <div id="embed" style="height: 600px; width: 75%; margin-left: auto; margin-right: auto; margin-top: 10px; border:0.5px solid black;"> </div>
```

index.js
```
   Smooch.init({
   integrationId: '<integration-id>',
   embedded: true
   });

   Smooch.render(document.getElementById('embed'));
```

Calling render outside of your init should do the trick! Please let me know if you're still running into issues and I'll be glad to take a look.
